language: python

matrix:
  include:
    python: 3.5.2
    sudo: true

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - pytest --cov=app/
  
after_success:
  - coveralls

cache: pip